name: Terraform Destroy ECS-App-Part3

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-north-1
  WORKING_DIR: ./ecs-app-part3

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (Apply)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::054424862519:role/github-terraform-apply-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Empty ECR Repository
        run: |
          run: |
          IMAGES=$(aws ecr list-images --repository-name app --query 'imageIds[*]' --output json)
          if [ "$IMAGES" != "[]" ]; then
            aws ecr batch-delete-image --repository-name app --image-ids "$IMAGES"
          fi
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ env.WORKING_DIR }}